//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(ProductTagsMetaData))]
    public partial class Product_Tags
    {
        public int ProductTagID { get; set; }
        public int ProductID { get; set; }
        public string ProductTag { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
