//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(SliderMetaData))]
    public partial class Slider
    {
        public int SliderID { get; set; }
        public string SliderTitle { get; set; }
        public string SliderImageName { get; set; }
        public System.DateTime SliderStartDate { get; set; }
        public System.DateTime SliderEndTime { get; set; }
        public bool SliderIsActive { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string SliderUrl { get; set; }
    }
}
