//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
namespace DataLayer
{
    public  class ProductsMetaData
    {
        [Key]
        public int ProductID { get; set; }

        [Display(Name = "Title")]
        [Required(ErrorMessage ="Please Enter Title:")]
        [MaxLength(350)]
        public string ProductTitle { get; set; }

        [Display(Name = "ShortDescription")]
        [Required(ErrorMessage = "Please Enter ShortDescription:")]
        [DataType(DataType.MultilineText)]
        [MaxLength(500)]
        public string ProductShortDesc { get; set; }

        [Display(Name = "Text")]
        [Required(ErrorMessage = "Please Enter Text")]
        [DataType(DataType.MultilineText)]
        //[AllowHtml]
        public string ProductText { get; set; }

        [Display(Name = "Price")]
        [Required(ErrorMessage = "Please Enter Price")]
        public int ProductPrice { get; set; }

        [Display(Name = "Image")]
        public string ProductImageName { get; set; }

        [Display(Name = "CreateDate")]
        [DisplayFormat(DataFormatString = "{0: yyyy/MM/dd}")]
        public System.DateTime RecordDate { get; set; }
    }
}