//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    public  class Product_GroupsMetaData
    {
         [Key]
        public int GroupID { get; set; }

        [Display(Name = "Group title")]
        [Required(ErrorMessage ="Plese Enter{0}")]
        public string GroupTitle { get; set; }

        public Nullable<int> ParentID { get; set; }
    }
}