//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace DataLayer
{
    public  class Product_CommentsMetaData
    {
        public int CommentID { get; set; }
        public int ProductID { get; set; }

        [Display(Name = "Name")]
        [Required(ErrorMessage = "Please Enter Name :")]
        public string UserName { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "Please Enter Email")]
        [EmailAddress(ErrorMessage = "Is Not Valid your Email:")]
        public string UserEmail { get; set; }

        [Display(Name = "WebSite")]
        public string UserWebSite { get; set; }

        [Display(Name = "Comment")]
        [Required(ErrorMessage = "Please Enter Comment ")]
        public string Comment { get; set; }
    }
}