//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace DataLayer
{
    internal class SliderMetaData
    {
        [Key]
        public int SliderID { get; set; }

        [Display(Name = "Title")]
        [Required(ErrorMessage = "Please Enter Title")]
        public string SliderTitle { get; set; }

        [Display(Name = "Image")]
        public string SliderImageName { get; set; }

        [Display(Name = "StartDate")]
        [DisplayFormat(DataFormatString = "{0: yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public System.DateTime SliderStartDate { get; set; }

        [Display(Name = "EndDate")]
        [DisplayFormat(DataFormatString = "{0: yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public System.DateTime SliderEndTime { get; set; }

        [Display(Name = "Status")]
        public bool SliderIsActive { get; set; }

        [Display(Name = "Url")]
        [Required(ErrorMessage = "Please Enter Url")]
        [Url(ErrorMessage ="Address is not valid")]
        public string SliderUrl { get; set; }
    }
}