//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System.ComponentModel.DataAnnotations;
    using System;

    public class UsersMetaData
    {
        [Key]
        public int UserID { get; set; }

        [Display(Name = "User Role")]
        public int RoleID { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public string UserActiveCode { get; set; }
        public bool UserIsActive { get; set; }
        public System.DateTime RegisterDate { get; set; }
    }
}